version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gianmarcolc99/practica5:1.0  
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - my_app_net

networks:
  my_app_net: