kind: Template
apiVersion: v1
metadata:
  name: apiexpress-template
  annotations:
    description: >-
      Platilla de despliegue para apiexpress
    tags: "express"
    openshift.io/documentation-url: "https://github.com/gianmarco99lc/practica5.git"
    openshift.io/suport-url: "https://github.com/gianmarco99lc/practica5.git"

parameters:
  - name: APP_NAME
    description: Nombre de applicación (Prefijo de todos los objetos).
    value: apiexpress 

  - name: DOMAIN_NAME
    description: Nombre de dominio para la publicación de la ruta.
    value: apiexpress.okd-dev.ucab.edu.ve

  - name: PROJECT_NAME
    description: Nombre de projecto
    value: pj-gleone-18

labels:
  app: "apiexpress"

objects:

  - kind: Service
    apiVersion: v1
    metadata:
      name: "apiexpress-appserver"
    spec:
      ports:
        - name: appserver
          port: 4000
          targetPort: 4000
      selector:
        app: "apiexpress-appserver"
    
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: apiexpress-appserver
      name: apiexpress-appserver
    spec:
      host: apiexpress.okd-dev.ucab.edu.ve
      port:
        targetPort: appserver
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: apiexpress-appserver
        weight: 100
      wildcardPolicy: None
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: "apiexpress-appserver"
    spec:
      replicas: 1 
      selector:
        matchLabels:
          app: "apiexpress-appserver"
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: "apiexpress-appserver"
        spec:
          containers:
            - image: 'gianmarcolc99/practica5:3.0'
              imagePullPolicy: Always
              name: appserver
              env:
                - name: NODE_ENV
                  value: production
              ports:
                - containerPort: 4000
                  protocol: TCP
              resources:
                limits:
                  memory: "256M"
                requests:
                  memory: "256M"
              volumeMounts:
                - name: apiexpress-volume
                  mountPath: /app/data 
                  subPath: data
          restartPolicy: Always
          volumes:
            - name: apiexpress-volume
              persistentVolumeClaim:
                claimName: "data"    
